# Group Project

In [1]:
import pandas as pd
import numpy as np

In [63]:
# import data
train = pd.read_csv('Project_train.csv')
test = pd.read_csv('Project_test.csv')

In [3]:
train.columns

Index(['customer', 'income', 'mailer', 'purchase', 'visits_so_far', 'week'], dtype='object')

In [4]:
# get resonse and independent variables
y = train['purchase']
X = train.drop(['purchase'], axis = 1)

In [5]:
# split data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
# normalize
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [7]:
# Now apply the transformations to the data
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

### relu, 500 neurons

In [8]:
# build MLP 
from sklearn.neural_network import MLPClassifier
# choose 3 layers with 200 neurons and 500 max iterations
mlp1 = MLPClassifier(activation='relu', hidden_layer_sizes=(500,500,500,500,500), max_iter=200, n_iter_no_change=50)

In [9]:
# fit the model
mlp1.fit(X_train,y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(500, 500, 500, 500, 500),
              learning_rate='constant', learning_rate_init=0.001, max_iter=200,
              momentum=0.9, n_iter_no_change=50, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [10]:
pred1 = mlp1.predict(X_test)

In [11]:
# evalution
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [12]:
print(confusion_matrix(y_test,pred1))

[[935 337]
 [411 317]]


In [13]:
print(classification_report(y_test,pred1))

              precision    recall  f1-score   support

           0       0.69      0.74      0.71      1272
           1       0.48      0.44      0.46       728

    accuracy                           0.63      2000
   macro avg       0.59      0.59      0.59      2000
weighted avg       0.62      0.63      0.62      2000



In [14]:
print(accuracy_score(y_test,pred1))

0.626


In [ ]:
mlp11 = MLPClassifier(activation='relu', hidden_layer_sizes=(500,500,500), max_iter=200, n_iter_no_change=50)

In [ ]:
mlp11.fit(X_train,y_train)

In [ ]:
pred11 = mlp1.predict(X_test)

In [ ]:
print(accuracy_score(y_test,pred11))

In [ ]:
mlp12 = MLPClassifier(activation='relu', hidden_layer_sizes=(500,500,300,300,500), max_iter=200, n_iter_no_change=50)

In [ ]:
mlp12.fit(X_train,y_train)

In [ ]:
pred12 = mlp1.predict(X_test)

In [ ]:
print(accuracy_score(y_test,pred12))

### logistic, 500 neurons

In [15]:
mlp2 = MLPClassifier(activation='logistic', hidden_layer_sizes=(500,500,500,500,500), max_iter=200, n_iter_no_change=50)

In [16]:
mlp2.fit(X_train,y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(500, 500, 500, 500, 500),
              learning_rate='constant', learning_rate_init=0.001, max_iter=200,
              momentum=0.9, n_iter_no_change=50, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [17]:
pred2 = mlp2.predict(X_test)

In [18]:
print(confusion_matrix(y_test,pred2))

[[1197   75]
 [ 562  166]]


In [19]:
print(classification_report(y_test,pred2))

              precision    recall  f1-score   support

           0       0.68      0.94      0.79      1272
           1       0.69      0.23      0.34       728

    accuracy                           0.68      2000
   macro avg       0.68      0.58      0.57      2000
weighted avg       0.68      0.68      0.63      2000



In [20]:
print(accuracy_score(y_test,pred2))

0.6815


### identity, 500 neurons

In [21]:
mlp3 = MLPClassifier(activation='identity', hidden_layer_sizes=(500,500,500,500,500), max_iter=200, n_iter_no_change=50)

In [22]:
mlp3.fit(X_train,y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='identity', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(500, 500, 500, 500, 500),
              learning_rate='constant', learning_rate_init=0.001, max_iter=200,
              momentum=0.9, n_iter_no_change=50, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [59]:
pred3 = mlp3.predict(X_test)

In [60]:
print(confusion_matrix(y_test,pred3))

[[1061  211]
 [ 418  310]]


In [61]:
print(classification_report(y_test,pred3))

              precision    recall  f1-score   support

           0       0.72      0.83      0.77      1272
           1       0.60      0.43      0.50       728

    accuracy                           0.69      2000
   macro avg       0.66      0.63      0.63      2000
weighted avg       0.67      0.69      0.67      2000



In [62]:
print(accuracy_score(y_test,pred3))

0.6855


### tanh, 500 neurons

In [27]:
mlp4 = MLPClassifier(activation='tanh', hidden_layer_sizes=(500,500,500,500,500), max_iter=200, n_iter_no_change=50)

In [28]:
mlp4.fit(X_train,y_train)

MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(500, 500, 500, 500, 500),
              learning_rate='constant', learning_rate_init=0.001, max_iter=200,
              momentum=0.9, n_iter_no_change=50, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [29]:
pred4 = mlp4.predict(X_test)

In [30]:
print(confusion_matrix(y_test,pred4))

[[1075  197]
 [ 433  295]]


In [31]:
print(classification_report(y_test,pred4))

              precision    recall  f1-score   support

           0       0.71      0.85      0.77      1272
           1       0.60      0.41      0.48       728

    accuracy                           0.69      2000
   macro avg       0.66      0.63      0.63      2000
weighted avg       0.67      0.69      0.67      2000



In [32]:
print(accuracy_score(y_test,pred4))

0.685


### voting

In [33]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier

In [34]:
rf = RandomForestClassifier(n_estimators=100, min_samples_leaf=13, min_samples_split=13, random_state=1)
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=13, min_samples_split=13,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=1, verbose=0,
                       warm_start=False)

In [35]:
pred = rf.predict(X_test)

In [36]:
print(accuracy_score(y_test,pred))

0.6835


In [ ]:
#from sklearn.linear_model import LogisticRegression
#lr = LogisticRegression()
#lr.fit(X_train, y_train)

In [ ]:
#pred = lr.predict(X_test)

In [ ]:
#print(accuracy_score(y_test,pred))

In [42]:
vc1 = VotingClassifier(estimators=[('mlp2', mlp2), ('mlp3', mlp3), ('mlp4', mlp4), ('rf', rf)], 
                       voting='hard')

In [43]:
vc1 = vc1.fit(X_train,y_train)

In [44]:
pred = vc1.predict(X_test)

In [45]:
print(confusion_matrix(y_test,pred))

[[1127  145]
 [ 481  247]]


In [46]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.70      0.89      0.78      1272
           1       0.63      0.34      0.44       728

    accuracy                           0.69      2000
   macro avg       0.67      0.61      0.61      2000
weighted avg       0.68      0.69      0.66      2000



In [47]:
print(accuracy_score(y_test,pred4))

0.685


In [48]:
test.columns

Index(['id', 'customer', 'income', 'mailer', 'visits_so_far', 'week'], dtype='object')

In [64]:
# drop id column
test1 = test.drop(['id'], axis = 1)

In [65]:
prediction = mlp3.predict(test1)

In [66]:
test['purchase'] = prediction

In [67]:
test.to_csv(r'/Users/shiyunwang/Desktop/NBA 4920/Group Project/test.csv')

### Adaboost

In [37]:
from sklearn.ensemble import AdaBoostClassifier

In [55]:
ab = AdaBoostClassifier(rf)

In [56]:
ab = ab.fit(X_train,y_train)

In [57]:
pred = ab.predict(X_test)

In [58]:
print(accuracy_score(y_test,pred))

0.638


## Bonus

### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

In [ ]:
pred = lr.predict(X_test)
pred

In [ ]:
print(confusion_matrix(y_test,pred))

In [ ]:
print(classification_report(y_test,pred))

In [ ]:
print(accuracy_score(y_test,pred))

### Classification Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
ct = DecisionTreeClassifier(min_samples_leaf=13, min_samples_split=13, random_state=1)

In [ ]:
ct.fit(X_train,y_train)

In [ ]:
pred = ct.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,pred))

In [ ]:
print(classification_report(y_test,pred))

In [ ]:
print(accuracy_score(y_test,pred))